// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPnfJ6e3BBvBb31z72FzWmV5fi1-VpQnY',
    appId: '1:429357919262:web:4f16c01c99ed20738ed20f',
    messagingSenderId: '429357919262',
    projectId: 'free-to-game-8e900',
    authDomain: 'free-to-game-8e900.firebaseapp.com',
    storageBucket: 'free-to-game-8e900.appspot.com',
    measurementId: 'G-C1KSTPCMKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuTSjZfmvvVZ0SDFlP7h8t3QVwORGyjdY',
    appId: '1:429357919262:android:9e8f4277acf9da838ed20f',
    messagingSenderId: '429357919262',
    projectId: 'free-to-game-8e900',
    storageBucket: 'free-to-game-8e900.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPnfJ6e3BBvBb31z72FzWmV5fi1-VpQnY',
    appId: '1:429357919262:web:0a06723713932a6e8ed20f',
    messagingSenderId: '429357919262',
    projectId: 'free-to-game-8e900',
    authDomain: 'free-to-game-8e900.firebaseapp.com',
    storageBucket: 'free-to-game-8e900.appspot.com',
    measurementId: 'G-Q3T3QH3MJV',
  );
}
